name: Step Motor Test Pipeline

on: [push]

jobs:
  analyze_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: List Files (Debug)
        # Dosyaların nerede olduğunu görmek için listeleyelim
        run: ls -R 

      - name: Install Cppcheck
        run: sudo apt-get update && sudo apt-get install -y cppcheck

      - name: Run Static Analysis
        # Nokta (.) yerine dosyanı direkt göstererek işi garantiye alalım
        # Makalede bahsedilen 'verifiable' kod denetimi
        run: cppcheck --enable=all --suppress=missingIncludeSystem newmain.c