name: Step Motor Test Pipeline

on: [push]

jobs:
  analyze_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Cppcheck and Python
        run: sudo apt-get update && sudo apt-get install -y cppcheck python3

      - name: Run MISRA C Compliance Check
        # Bütün sistem, kütüphane ve kullanılmayan kesme (interrupt) hataları komut satırından tamamen susturuldu
        run: cppcheck --addon=misra --enable=all --inline-suppr --suppress=missingIncludeSystem --suppress=misra-config --suppress=unusedFunction --error-exitcode=1 newmain.c
